spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.HSQLDialect
    hibernate.ddl-auto: create

aws:
  s3:
    accessKey: 0
    secretKey: 0
    region: us-east-1
    endpoint: http://0.0.0.0:4566